### ISSUE TITLE
Question about backup target

### ISSUE THREAD

**Issue by devdattakulkarni** [Percona-Lab/percona-openshift#1]
Hi,

I found this repo from the webinar link: https://www.percona.com/resources/technical-presentations/mysqlpxc-proxysql-kubernetes-how-they-work-together-percona

In our use-case we need Percona on OpenShift. We want to take periodic backups and store them in S3. In the documentation (README and the slide-deck), backup is mentioned but I could not find information about the backup target. I was wondering where are the backups stored in the current setup?

Thanks for the help!

**Comment by vadimtk** [comment]
Hi,

I added backup docs in the section
https://github.com/Percona-Lab/percona-openshift/blob/master/README.md#backups

Does it resolve your question?
