### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by airdos360** [Percona-Lab/percona-openshift#2]
I am using the Deploy YAML by using:

mysql-configmap.yaml
secret.yaml
pxc.yaml
proxysql-pxc.yaml

Everything works till I add the proxy.   The proxy gets:

Exec lifecycle hook ([/usr/bin/peer-list -on-start="/usr/bin/add_cluster_nodes.sh" -service=perconacluster]) for Container "percona-proxysql" in Pod "percona-proxysql-0_mysql(03b75752-9d8e-11e8-9b71-00155d06750e)" 2018/08/11 17:43:12 Peer list updated was [] now [percona-0.perconacluster.mysql.svc.cluster.local percona-1.perconaclustfailed - error: command '/usr/bin/peer-list -on-start="/usr/bin/add_cluster_nodes.sh" -service=perconacluster' exited with 137: 2018/08/11 17:43:12 Peer finder enter 2018/08/11 17:43:12 Determined Domain to be mysql.svc.cluster.local er.mysql.svc.cluster.local percona-2.perconacluster.mysql.svc.cluster.local] 2018/08/11 17:43:12 execing: "/usr/bin/add_cluster_nodes.sh" with stdin: percona-0.perconacluster.mysql.svc.cluster.local percona-1.perconacluster.mysql.svc.cluster.local percona-2.perconacluster.mysql.svc.cluster.local , message: "2018/08/11 17:43:12 Peer finder enter\n2018/08/11 17:43:12 Determined Domain to be mysql.svc.cluster.local\n2018/08/11 17:43:12 Peer list updated\nwas []\nnow [percona-0.perconacluster.mysql.svc.cluster.local percona-1.perconacluster.mysql.svc.cluster.local percona-2.perconacluster.mysql.svc.cluster.local]\n2018/08/11 17:43:12 execing: \"/usr/bin/add_cluster_nodes.sh\" with stdin: percona-0.perconacluster.mysql.svc.cluster.local\npercona-1.perconacluster.mysql.svc.cluster.local\npercona-2.perconacluster.mysql.svc.cluster.local\n"	

All the names seem correct but it can't find the peers?

Also, when I delete and update the pxc.yaml it will not restart.   I have to delete the data files then everything goes back to running with 3 pods.

Also, I am setting the PXC to 300Gi.    How much space is needed for the Proxy?

**Comment by delgod** [comment]
@airdos360, I cannot reproduce the issue
few megabytes should be enough for ProxySQL

please consider using https://github.com/Percona-Lab/percona-xtradb-cluster-operator
