### ISSUE TITLE
Cluster check password env var missing (helm deployment)

### ISSUE THREAD

**Issue by Philio** [Percona-Lab/percona-openshift#23]
With the latest images, since this change I assume: https://github.com/Percona-Lab/percona-openshift/commit/ce9663e478c24e1ecdf6dc6e1517f74084dfc16e

The env var `CLUSTERCHECK_PASSWORD` is missing from the node, so readiness check fails if you have changed the password.

The YAML editor in IntelliJ is flagging duplicate `env` blocks, combining them into a single block seemed to resolve the problem.

E.g.

        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "percona.fullname" . }}-secrets
              key: monitor
    {{ if eq .Values.kind "cluster" }}
        - name: CLUSTERCHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "percona.fullname" . }}-secrets
              key: clustercheck
    {{ end }}

**Comment by delgod** [comment]
fixed in https://github.com/Percona-Lab/percona-openshift/pull/25
